# Generated by Django 3.0.5 on 2021-01-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_remove_cart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('address', models.CharField(max_length=1000)),
                ('order_id', models.CharField(max_length=200)),
                ('payment_request_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=1000)),
                ('instrument_type', models.CharField(max_length=1000)),
                ('billing_instrument', models.CharField(max_length=1000)),
                ('long_url', models.CharField(max_length=1000)),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Cart')),
            ],
        ),
    ]
